DGL_BACKEND_SDL2_DIR := $(DGL_BACKENDS_DIR)/sdl2

DGL_BACKEND_SDL2_SOURCES := $(shell find $(DGL_BACKEND_SDL2_DIR) -name '*.cpp' -printf '%T@\t%p\n' | sort -k 1nr | cut -f2-)
DGL_BACKEND_SDL2_OBJECTS := $(DGL_BACKEND_SDL2_SOURCES:%.cpp=$(DGL_BUILD_DIR)/%.o)

DGL_BACKEDN_SDL2_BUILD_DIR := $(DGL_BUILD_DIR)/$(DGL_BACKENDS_DIR)/sdl2

OBJECTS += $(DGL_BACKEND_SDL2_OBJECTS)
INCLUDES += -I$(DGL_BACKEND_SDL2_DIR) 

LIBS += -lSDL2

.PHONY: $(DGL_BACKEDN_SDL2_BUILD_DIR)

dirs: $(DGL_BACKEDN_SDL2_BUILD_DIR)

$(DGL_BUILD_DIR)/$(DGL_BACKENDS_DIR)/sdl2.a: $(DGL_BACKEND_SDL2_OBJECTS)
	@echo "Compiling $(DGL_BACKEND_SDL2_OBJECTS) -> $@"
	@ar rcs $@ $^

$(DGL_BUILD_DIR)/$(DGL_BACKENDS_DIR)/sdl2/%.o: $(DGL_BACKEND_SDL2_DIR)/%.cpp
	@echo "Compiling: $< -> $@"
	@$(CMD_PREFIX)$(CXX) $(CXXFLAGS) $(CORE_CXXFLAGS) -I$(DGL_CORE_DIR) $(CORE_INCLUDES) -MP -MMD -c $< -o $@

